### ISSUE TITLE
Two-finger horizontal scroll does not work in history bar

### ISSUE THREAD

**Issue by TomFrost** [pravdomil/Native-Trackpad#12]
I updated to the April 2023 major Fusion 360 release today and it totally broke gesture-based panning for me. I found this add-in when googling for a workaround, and it has been a GODSEND. Thank you!

The one and only issue I've noticed so far is that I can no longer scroll through the horizontal history pane with two fingers. Instead of scrolling, this gesture pans the model interface as though you didn't have the pointer over top of the history bar. The only way to scroll that bar now is to click and drag the scrollbar at the top of that view. Minor, but worth note. I have zero experience with add-in coding, but I'm happy to take a stab at this if someone wants to point me at a good place to start with this one.

**Comment by jkotowicz1** [comment]
It's the same as with left Project column - just hold Shift and then you can scroll these panes with gestures. With inertial scrolling it's more enjoyable than grabbing the scrollbar.

**Comment by pravdomil** [comment]
added to readme
