### ISSUE TITLE
April 2023 update breaks orbit

### ISSUE THREAD

**Issue by thirtytwobits** [pravdomil/Native-Trackpad#13]
shift+two-finger orbit no longer works after the big April 2023 update.

**Comment by joreyaesh** [comment]
Glad to hear it wasn't just me - I've been going crazy trying to get orbit to work.

**Comment by nmsmith22389** [comment]
Anyone have any luck?

I can't use their stupid "Native Trackpad" option because it makes panning *impossibly* slow.

**Comment by Yutao-Jin** [comment]
does anyone tried the native trackpad in the preview, does it wprk for you guys. why I turned it on it broke everything

**Comment by Yutao-Jin** [comment]
> Anyone have any luck?
> 
> I can't use their stupid "Native Trackpad" option because it makes panning _impossibly_ slow.

does the standard trackpad implmentation work for you, for me it only zoom when you pan. I can do any thong with it now. It used to be laggy bust at least working

**Comment by thirtytwobits** [comment]
I can't use their experimental, native trackpad support because it doesn't provide an inverted pan. Also, the panning is stupid-slow.

Also. I got it working again. I'll fork this repo and post the fix.

**Comment by thirtytwobits** [comment]
Here's the fix : https://github.com/scottdarch/Native-Trackpad/releases/tag/v2.0.15995

(sorry, I'm using my work account here by accident. The link is to my personal account).

**Comment by hokoon** [comment]
@thirtytwobits not working (intel imac 13.3.1)

**Comment by it-ony** [comment]
@thirtytwobits, I was comparing your changes to the master branch. Can you please create a PR. Also, please have a look on https://github.com/mertrois/Native-Trackpad/pull/10, the changes look similar.

@pravdomil any chance you get those merged and create a new release. Fusion by heart is not usable without your addin.

**Comment by daVid0n** [comment]
hey mates, so glad i found this repo, but shift+two finger = orbit still isnt working for me, any idea or is this being worked on? i cant use fusion like this any more, cant understand why they changed the behaviour at all. thx to your great work so far!!

I'm on M1 macOS 13.4 ventura

edit: have to admit that it works flawlessly when turning fusion back to using native trackpad recognition without lagging

**Comment by thirtytwobits** [comment]
I have ambitions to pick up this work but not time right now. I too am super-frustrated by Autodesk's lack of support for the mac trackpad. Their "native" solution is abysmal and I don't know why they just don't pull this code in and make it part of the core offering.

**Comment by daVid0n** [comment]
i totally feel you! its a mess momentarily. 
but the big upgrade with native m1 support should come soon, maybe we will have this solved by then, also 🤞

**Comment by hokoon** [comment]
That's enough... I gave up waiting for the update and ordered a SpaceMouse from 3D Connexion.

**Comment by pravdomil** [comment]
check new https://github.com/mertrois/Native-Trackpad/releases

**Comment by pravdomil** [comment]
orbit has been fixed!

**Comment by hokoon** [comment]
This went from
Pan✅ Orbit❌
to
Pan❌ Orbit❌ 
I think i'll have to stick with the old NativeTrackpad2
iMac Retina 5K, 3.8 GHz 8-Core Intel Core i7, Ventura 13.4 (22F66)

**Comment by pravdomil** [comment]
turn off Use gesture-based view navigation?

restart fusion?

**Comment by hokoon** [comment]
yes, turned off, install-restart twice.
seems like the add-in won't start, I try click "Run" but nothing happen.

**Comment by pravdomil** [comment]
that can be permission issue
<img width="315" alt="image" src="https://github.com/mertrois/Native-Trackpad/assets/2387356/3faa5df0-99bf-40d2-8fb4-2608f6d8e0b5">

it should look like so
<img width="454" alt="image" src="https://github.com/mertrois/Native-Trackpad/assets/2387356/d7e3832c-4dec-484f-bb77-4be6753a7c35">

**Comment by hokoon** [comment]
My Security section is the same "App store and identified developers".

<img width="880" alt="Screenshot 2567-01-12 at 05 26 13" src="https://github.com/mertrois/Native-Trackpad/assets/30663767/d159b9e9-6352-4473-86d0-b8c7d161e453">

**Comment by pravdomil** [comment]
I can connect to your mac and fix it if you want

**Comment by hokoon** [comment]
Don't worry, I already have the SpaceMouse. Thanks.
