### ISSUE TITLE
Rotation doesn't work after Mac wokeup

### ISSUE THREAD

**Issue by it-ony** [pravdomil/Native-Trackpad#2]
First: Without your extension, Fusion isn't usable on a Mac with a trackpad. So, thank you very much for providing this plugin.

The plugin stops working after the mac went to sleep and woke up again. Only a restart of Fusion, will make the rotation via trackpad possible again.

**Comment by pravdomil** [comment]
can't reproduce on macOS 10.13.2

**Comment by it-ony** [comment]
Yesterday, I couldn't as well. I try to find a way to reproduce it.

**Comment by candera** [comment]
I was also seeing this. However, selecting the orbit tool, orbiting a bit, and then going back into regular mode restored the ability to two-finger orbit.

If this works consistently I consider it an acceptable workaround. In any event, thanks for the plugin - this fixes one of the most annoying things about Fusion!

**Comment by pravdomil** [comment]
try new release!
https://github.com/mertrois/Native-Trackpad/releases
