### ISSUE TITLE
Installation via installer not working

### ISSUE THREAD

**Issue by it-ony** [pravdomil/Native-Trackpad#4]
After the latest update from Fusion, forcing to install the app not via the Mac App Store, the trackpad was not usable at all. After uninstalling the app completely and also Native trackpad, I installed both, but still had a shitty UX when navigating with the trackpad. 

After a while I figured out, that the native trackpad addin was not installed. I traced down the the modified files during installation and didn't find file moved into the correct addin dir of fusion. 

What really helped, was the documentation about the [manual installation](https://github.com/pravdomil/Native-Trackpad#manual-install). Trackpad can be used again and Fusion is now usable again. Still the addon page on autodesk should provide details for manual installation or the installer might need to be reworked.

**Comment by pravdomil** [comment]
I have updated AppStore description.
