### ISSUE TITLE
Reverse pan

### ISSUE THREAD

**Issue by ardiilves** [pravdomil/Native-Trackpad#6]
Got it working on Mac OS Catalina but would like to invert pan function. Is it possible?

**Comment by pravdomil** [comment]
idk

**Comment by piotrm0** [comment]
Switching trackpad scroll direction in System Preferences does it but then it messes with scrolling everywhere else.

**Comment by piotrm0** [comment]
Does these lines have anything to do with it:

https://github.com/pravdomil/Native-Trackpad/blob/1babd5b0ecfae3ff3a184b83caa943e24ff3935b/xcode/NativeTrackpad.mm#L62

https://github.com/pravdomil/Native-Trackpad/blob/1babd5b0ecfae3ff3a184b83caa943e24ff3935b/xcode/NativeTrackpad.mm#L68

**Comment by NCRonB** [comment]
@piotrm0 Indeed they do. I moved the `* -1` to `deltaY` and rebuilt. Now panning is reversed.

**Comment by pravdomil** [comment]
it mirrors the system settings
