### ISSUE TITLE
Unable to use two finger scroll on left side data panel

### ISSUE THREAD

**Issue by albertcai101** [pravdomil/Native-Trackpad#8]
Two finger scroll over the data panel pans the viewport instead. To scroll, the thin scroll bar on the right edge of the data panel must be tragged.

**Comment by albertcai101** [comment]
Sorry, missed explanation on README

**Comment by candera** [comment]
@pravdomil Did you see the comment in the README? `You can't no longer scroll in Data panel, in order to scroll hold Command key.`
